version: '3.9'
services:
  typo3-php56:
    build:
      context: .
      dockerfile: ./docker-typo3/Dockerfile.php56
    volumes:
      - ./app:/var/www/html
#    depends_on:
#      - mysql-db
#  php-fpm:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    volumes:
#      - ./app:/var/www/html
#    depends_on:
#      - mysql-db

#  apache-httpd:
#    build:
#      context: .
#      dockerfile: ./apache/Dockerfile
#    volumes:
#      - ./app:/var/www/html
#    ports:
#      - "8888:80"
#    depends_on:
#      - php-fpm
#      - mysql-db
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8889:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
