version: '3.9'
services:
  php-fpm:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    volumes:
      - ./wwwroot:/var/www/html
    depends_on:
      - mysql-db

  apache-httpd:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    volumes:
      - ./wwwroot:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - mysql-db
  # configure mysql volumes etc. https://hub.docker.com/r/cytopia/mysql-5.6
  mysql-db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./mysqld/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8889:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
