version: '3.9'
services:
#  typo3-php56:
#    build:
#      context: .
#      dockerfile: ./docker-typo3/Dockerfile.php56.anorak
#    volumes:
#      - ./app:/var/www/html
#    depends_on:
#      - mysql-db
  php-fpm:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql-db

  apache-httpd:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - mysql-db
  mysql-db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8889:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
